name: test_eden_farm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  firebase_core: ^1.14.1
  firebase_auth: ^3.3.14
  google_fonts: ^2.3.1
  cached_network_image: ^3.2.0
  charts_flutter: ^0.12.0
  toggle_switch: ^2.0.1
  cloud_firestore: ^3.1.13

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

